### ISSUE TITLE
Invite box jumps while searching

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2628]
The invite box is rerendered in a way that makes the page jump.
 
![jumpy-input](https://user-images.githubusercontent.com/109692/125856364-a990559e-d63a-48f5-a811-19b45b3a5e43.gif)

**Comment by AdamPrins** [comment]
The issue appears to be that the loading animation is larger than the `No users in this organization` text, so the page has to make more space. 

On live, I'm having only the footer perform any jumping though, which is less problematic than the behaviour displayed here. 

I'll do up a pr where the `No users in this organization` is given a similar high to the loading, so that should fix it.
