### ISSUE TITLE
Switching locales breaks landing page summary cards

### ISSUE THREAD

**Issue by lcampbell2** [canada-ca/tracker#2737]
**Describe the bug**
as described with the logged error: `TypeError: Cannot read property 'name' of undefined`

**To Reproduce**
1. Sign in to Tracker
2. Navigate to Landing page
3. Switch locales

**Expected behavior**
App should not break

**Comment by AdamPrins** [comment]
Okay, I've done some digging and it seems the API behaves differently for the two queries
`ORG_DETAILS_PAGE` and `WEB_AND_EMAIL_SUMMARIES`

For the `ORG_DETAILS_PAGE`, inside the categories section, the name is always in English
```
"categories":[
   {
      "name":"pass",
      "count":0,
      "percentage":0,
      "__typename":"SummaryCategory"
   },
```

For the `WEB_AND_EMAIL_SUMMARIES`, inside the categories section, the name is always in English
```
"categories":[
   {
      "name":"passer",
      "count":1062,
      "percentage":11.5,
      "__typename":"SummaryCategory"
   },
```

So when the SummaryCard.js tries to use the name field, it can't find anything
`title: categoryDisplay[name].name,`

Since the CatagoryDisplay only has English keys
```
        fail: {
          name: t`Non-compliant TLS`,
          color: colors.weak,
        },
        pass: {
          name: t`Compliant TLS`,
          color: colors.strong,
        },
        unscanned: {
          name: t`Unscanned`,
          color: colors.gray['400'],
        },
```

The best fix is probably to have the API return consistently in English like the current `ORG_DETAILS_PAGE` query does.

I could hack it a little by doing something like this:
`CatagoryDisplay[passer]=CatagoryDisplay[pass]`

**Comment by FestiveKyle** [comment]
https://github.com/canada-ca/tracker/tree/api-dont-translate-summary-names
