### ISSUE TITLE
Favicon Issues When Viewing Organizations, and Individual DMARC Summaries

### ISSUE THREAD

**Issue by nsdeschenes** [canada-ca/tracker#2825]
**Describe the bug**
The default canada.ca favicon is being used on certain pages instead of the Tracker specific favicon.

**Expected behavior**
The expected behaviour is the Tracker Favicon is used.

**Screenshots**
![Screenshot from 2021-08-12 06-30-01](https://user-images.githubusercontent.com/7891920/129174026-6036ea1e-f573-4231-8126-5d80e2aa2130.png)![Screenshot from 2021-08-12 06-29-35](https://user-images.githubusercontent.com/7891920/129174033-46fa1132-1364-4bfe-afcb-898dfd16aad1.png)

**Comment by AdamPrins** [comment]
I have the favicon if I navigate to the page normally, but if I reload the page I get no favicon 
(Firefox)
<img width="290" alt="Screen Shot 2021-08-12 at 7 16 10 AM" src="https://user-images.githubusercontent.com/55841241/129187971-de741aee-e694-4d8b-adc0-7f6c96a9bf6b.png">

**Comment by AdamPrins** [comment]
It fails to load on the DMARC because of no javascript?

/Organizations
<img width="1279" alt="Screen Shot 2021-08-12 at 7 22 04 AM" src="https://user-images.githubusercontent.com/55841241/129188693-2460212f-3531-467f-800b-c33b6ea9e6db.png">

/DMARC Report
<img width="1280" alt="Screen Shot 2021-08-12 at 7 23 22 AM" src="https://user-images.githubusercontent.com/55841241/129188840-e3274ba2-0215-4e35-8cb8-9677382d378f.png">

And yes, I am getting the same errors on the summary page

**Comment by AdamPrins** [comment]
seems to occur on any page that has some sort of token in the url
```
<PrivatePage
    path="/organizations/:orgSlug"
```
organization/org
domains/domain
domains/domain/dmarc-report
reset-password/token

reset-password without the token loads properly.

**Comment by AdamPrins** [comment]
Okay, I think I have the issue.

They are only going up one level to find the images, and if you have the extra token, that isn't high enough.
/organizations
<img width="289" alt="Screen Shot 2021-08-12 at 7 48 48 AM" src="https://user-images.githubusercontent.com/55841241/129191773-3ecf34d3-3ea9-4df1-80af-c25637fbff08.png">

/domains/domain
<img width="329" alt="Screen Shot 2021-08-12 at 7 48 56 AM" src="https://user-images.githubusercontent.com/55841241/129191778-fd038e09-a292-40a4-9dd5-9e01ddcf351f.png">
