### ISSUE TITLE
Add the functionality for users to audit the adding/removing and compliancy

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3424]
Add the functionality for users to audit their orgs logs for CRUD on org domains.

Note: RBAC for CRUD of org domains. And how we monitor when being abused.

**Comment by CADbryon** [comment]
Damien to speak with Rahim.

**Comment by h701h** [comment]
1.	There is a want to allow users/orgs the ability to decommission their domains
2.	There is a need to allow users to audit other users actions within their organization. This includes when domains are get tagged with info and when removed from being scanned for compliance.

There is a need to drive more people to the site, but to also enrich our current set of domains with data that mattersTherefore, we are proposing to allow users to calibrate their digital footprints by tagging addresses as “production”. This allows individuals and orgs to calibrate and report on what is important to them. With this change we achieve all the requirements above and give users: 
1.	an incentive to add domains
2.	an incentive to tune their digital footprints (much like how a security rating services would).
3.	An ability to present bulk lists of domains to be ‘exempt’ from the ITPIN for GCEARB consumption. 

This issue is closed and merged into https://github.com/canada-ca/tracker/issues/3667
