### ISSUE TITLE
Work to get Tracker Compliant

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3553]
Use our own tools and make the tracker environments compliant with the rules we are tracking. If impossible let's explain this via a blog post. 

- [x] alpha
- [x] prod
- [ ] blog post needed?

![Image](https://user-images.githubusercontent.com/74711155/200906885-d720feeb-2a18-4c4b-a65f-82f6025cba10.png)

**Comment by FestiveKyle** [comment]
tracker.canada.ca:
- Failing HTTPS:
  - istio should be redirecting http traffic to https - http traffic is not actually being served on prod. This may be a limitation outside of the deployment. I think #4131 will fix this.
- Failing protocols:
  - Needs investigating
- Failing DKIM:
  -  Wildcard dkim record in place. API and UI currently do not support adding wildcard (fixed in #4134). This should put us in a passing state.

tracker.alpha.canada.ca:
  - Failing curves
    - Default curve in istio is causing curves to fail. I think we can make use of an EnvoyFilter to fix this (the section "alternative solution" [here](https://github.com/istio/istio/issues/41645). This feature may be added directly to the istio gateway api eventually (https://github.com/istio/istio/issues/41645)
  - Failing protocols
    - needs investigating
  - Failing DKIM
    - Wildcard dkim record in place. Same answer as for tracker.canada.ca
