### ISSUE TITLE
Transition to Artifact Registry

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3959]

**Comment by FestiveKyle** [comment]
Copied images from Container Registry to Artifact Registry on Feb 19 2024 and changed for new images to be pushed to Artifact Registry. Images at Container Registry were also set to Private. Everything has been working since then. Going ahead and deleting the underlying bucket for Container Registry now.

**Comment by FestiveKyle** [comment]
Bucket for Container Registry has been deleted.
