### ISSUE TITLE
Handle wildcard DNS records properly

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4180]
A wildcard DNS record is a record in a DNS zone that will match requests for non-existent domain names. A wildcard DNS record is specified by using a * as the leftmost label (part) of a domain name, e.g. *. example.com.

Remember that there will be actual domains behind a wildcard DNS entries. 

- [ ] When a wildcard is detected. Let the user know.  bellabella.bc.rcmp-grc.gc.ca as *.bc.rcmp-grc.gc.ca

**Comment by FestiveKyle** [comment]
Something to note for this - we can't be certain if the response we get back from the DNS is for a wildcard or a separate specific domain. 

We have a few approaches we could use for this depending on what we want to achieve. 
1. We could check if there is a wildcard sibling at the same level and simply show that the results may be from the wildcard domain.
2. We could compare the `A` records of domains being added against wildcard at the same level. 
3. For web servers, we could compare HTTP response code and content from a new domain against the result we get from a (presumably) wildcard domain (ex. "ad2jkl2djakld39034.example.com").

We should look into what the largest issues are regarding wildcards - email results, web results, skewed summary numbers due to duplicates, or do we simply want to show the user that a wildcard resolver exists as a sibling for a domain.

**Comment by FestiveKyle** [comment]
Todo: Research wildcard domains more. 
- Do issues exist? (security etc...) 
- Why use one?

**Comment by h701h** [comment]
At the moment we "simply want to show the user that a wildcard resolver exists as a sibling for a domain"
